# Generated by Django 6.0.3 on 2026-03-18 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
        ('vocabulary', '0005_word_audio_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='language',
            field=models.CharField(default='english', max_length=50),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vocabulary.lesson'),
        ),
        migrations.AddField(
            model_name='flashcardreview',
            name='ease_factor',
            field=models.FloatField(default=2.5),
        ),
        migrations.AddField(
            model_name='flashcardreview',
            name='repetitions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='flashcardreview',
            constraint=models.UniqueConstraint(fields=('user', 'flashcard'), name='unique_user_flashcard_review'),
        ),
    ]
