# Generated by Django 6.0.3 on 2026-03-18 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mistakes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mistake',
            name='username',
        ),
        migrations.AddField(
            model_name='mistake',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mistake',
            name='last_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mistake',
            name='mistake_type',
            field=models.CharField(choices=[('quiz', 'Quiz'), ('grammar', 'Grammar'), ('vocabulary', 'Vocabulary')], default='quiz', max_length=20),
        ),
        migrations.AddField(
            model_name='mistake',
            name='review_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mistake',
            name='source_module',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='mistake',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mistakes', to=settings.AUTH_USER_MODEL),
        ),
    ]
