# Generated by Django 6.0.1 on 2026-01-25 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DialogMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DialogNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('romaji_text', models.TextField(blank=True)),
                ('english_text', models.TextField(blank=True)),
                ('is_user_turn', models.BooleanField(default=False)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='dialog.dialogmission')),
            ],
        ),
        migrations.CreateModel(
            name='DialogChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('romaji_text', models.CharField(blank=True, max_length=200)),
                ('english_text', models.CharField(blank=True, max_length=200)),
                ('feedback', models.TextField(blank=True)),
                ('next_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dialog.dialognode')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='dialog.dialognode')),
            ],
        ),
    ]
