# Generated by Django 6.0.3 on 2026-03-17 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Idiom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(max_length=200)),
                ('meaning', models.TextField()),
                ('example', models.TextField()),
                ('language', models.CharField(max_length=50)),
            ],
        ),
    ]
