# Generated by Django 6.0.3 on 2026-03-18 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idioms', '0001_initial'),
        ('vocabulary', '0005_word_audio_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idiom',
            name='language',
        ),
        migrations.AddField(
            model_name='idiom',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vocabulary.lesson'),
        ),
        migrations.AddField(
            model_name='idiom',
            name='source_language',
            field=models.CharField(default='english', max_length=50),
        ),
        migrations.AddField(
            model_name='idiom',
            name='target_language',
            field=models.CharField(default='english', max_length=50),
        ),
    ]
