# Generated by Django 6.0.1 on 2026-02-04 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grammar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grammarcheck',
            name='english_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='grammarcheck',
            name='romaji_text',
            field=models.TextField(blank=True),
        ),
    ]
