# Generated by Django 6.0.1 on 2026-02-08 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grammar', '0002_grammarcheck_english_text_grammarcheck_romaji_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrammarError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=50)),
                ('error_code', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('example_correct', models.TextField()),
                ('example_incorrect', models.TextField()),
            ],
        ),
    ]
