# Generated by Django 6.0.3 on 2026-03-18 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_manager', '0001_initial'),
        ('vocabulary', '0005_word_audio_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='audio_type',
            field=models.CharField(choices=[('pronunciation', 'Pronunciation'), ('slow_mode', 'Slow Mode'), ('voice_recording', 'Voice Recording')], default='pronunciation', max_length=20),
        ),
        migrations.AddField(
            model_name='audiofile',
            name='duration_seconds',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='audiofile',
            name='is_slow_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='audiofile',
            name='language',
            field=models.CharField(default='english', max_length=50),
        ),
        migrations.AddField(
            model_name='audiofile',
            name='linked_word',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vocabulary.word'),
        ),
        migrations.AddField(
            model_name='audiofile',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='audiofile',
            name='transcript',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='audiofile',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
