# Generated by Django 6.0.1 on 2026-02-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='english_text',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='answer',
            name='example_sentence_english',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='example_sentence_romaji',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='romaji_text',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='english_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='example_sentence_english',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='example_sentence_romaji',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='romaji_text',
            field=models.TextField(blank=True),
        ),
    ]
