# Generated by Django 6.0.1 on 2026-02-04 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_answer_english_text_answer_example_sentence_english_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
