# Generated by Django 6.0.3 on 2026-03-18 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessons_completed', models.IntegerField(default=0)),
                ('quizzes_taken', models.IntegerField(default=0)),
                ('average_quiz_score', models.FloatField(default=0.0)),
                ('vocabulary_learned', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='language',
            field=models.CharField(default='english', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='completedlesson',
            constraint=models.UniqueConstraint(fields=('user', 'lesson'), name='unique_completed_lesson_per_user'),
        ),
        migrations.AddConstraint(
            model_name='uservocabulary',
            constraint=models.UniqueConstraint(fields=('user', 'vocab'), name='unique_user_vocab'),
        ),
        migrations.AddField(
            model_name='progresssnapshot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
