# Generated by Django 6.0.3 on 2026-03-18 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='username',
        ),
        migrations.AddField(
            model_name='achievement',
            name='category',
            field=models.CharField(choices=[('milestone', 'Milestone'), ('first_spoken_sentence', 'First Spoken Sentence'), ('mastered_word', 'Mastered Word')], default='milestone', max_length=40),
        ),
        migrations.AddField(
            model_name='achievement',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='achievement',
            name='title',
            field=models.CharField(blank=True, default='Achievement', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='achievement',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL),
        ),
    ]
