# Generated by Django 6.0.3 on 2026-03-18 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreference',
            name='username',
        ),
        migrations.AddField(
            model_name='userpreference',
            name='current_path',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='current_step',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='guided_prompts_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='navigation_progress',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='step_by_step_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preference', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='difficulty',
            field=models.CharField(default='beginner', max_length=50),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='learning_style',
            field=models.CharField(default='visual', max_length=100),
        ),
    ]
