# Generated by Django 6.0.1 on 2026-01-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='description',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='word',
            name='audio_url',
        ),
        migrations.RemoveField(
            model_name='word',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='word',
            name='text',
        ),
        migrations.RemoveField(
            model_name='word',
            name='translation',
        ),
        migrations.RemoveField(
            model_name='word',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='word',
            name='english_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='romaji_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='word_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
