# Generated by Django 6.0.1 on 2026-02-08 17:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0003_lesson_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='english_text',
        ),
        migrations.RemoveField(
            model_name='word',
            name='example_sentence',
        ),
        migrations.RemoveField(
            model_name='word',
            name='romaji_text',
        ),
        migrations.RemoveField(
            model_name='word',
            name='word_text',
        ),
        migrations.AddField(
            model_name='word',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='word',
            name='difficulty',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='word',
            name='english',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='word',
            name='mastery_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='word',
            name='romaji',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='word',
            name='script',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='word',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
