# Generated by Django 6.0.1 on 2026-03-18 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0004_remove_word_english_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='audio_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
