# Generated by Django 6.0.3 on 2026-03-18 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placementtest',
            name='user_name',
        ),
        migrations.AddField(
            model_name='placementtest',
            name='language',
            field=models.CharField(default='english', max_length=50),
        ),
        migrations.AddField(
            model_name='placementtest',
            name='recommended_course',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='placementtest',
            name='result_breakdown',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='placementtest',
            name='taken_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='placementtest',
            name='test_name',
            field=models.CharField(default='general', max_length=100),
        ),
        migrations.AddField(
            model_name='placementtest',
            name='total',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='placementtest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='placement_tests', to=settings.AUTH_USER_MODEL),
        ),
    ]
